version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - default-jdk
    - graphviz
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - bash docs/pre_install.sh

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py